### ISSUE TITLE
Upgrade eslint v9 need migrate your config file

### ISSUE THREAD

**Issue by TianbinTobin** [cawa-93/vite-electron-builder#1002]
```
$ eslint . --ext js,mjs,cjs,ts,mts,cts,vue
Invalid option '--ext' - perhaps you meant '-c'?
You're using eslint.config.js, some command line flags are no longer available. Please see https://eslint.org/docs/latest/use/command-line-interface for details.
```

**Comment by cawa-93** [comment]
Pr welcome

**Comment by theorib** [comment]
In the meantime `eslint` is currently broken on this repository. The `eslint` version on `package.json` is currently **v9.8.0** but all `eslint` config files in the repository are incompatible with that version. They are only compatible with **eslint v8 or under**, ever since they changed the config file structure to the flat config file. I suggest a regression to bring `eslint` to the latest compatible version (v8.57.0). I can open a Pr for that.
