### ISSUE TITLE
dynamic import() which is available in all CommonJS modules.

### ISSUE THREAD

**Issue by xuya227939** [cawa-93/vite-electron-builder#1017]
**Describe the bug**

`npm run compile`

error

`⨯ Unable to `require`  moduleName=/Users/jiang/Desktop/vite-electron-builder-main/electron-builder.mjs message=require() of ES Module /Users/jiang/Desktop/vite-electron-builder-main/electron-builder.mjs not supported.
Instead change the require of /Users/jiang/Desktop/vite-electron-builder-main/electron-builder.mjs to a dynamic import() which is available in all CommonJS modules.`

**To Reproduce**
1. npm run compile

**Comment by cawa-93** [comment]
What node version do you use?

**Comment by xuya227939** [comment]
node -v
v20.14.0

@cawa-93

**Comment by xuya227939** [comment]
and macOS Version is 15.0.1 @cawa-93

**Comment by cawa-93** [comment]
Does it work on node v23 ?

**Comment by cawa-93** [comment]
That's because I tested it only on node v23 and do not realize I used [experimental feature](https://joyeecheung.github.io/blog/2024/03/18/require-esm-in-node-js/). In your case, you can simply rewrite `electron-builder.mjs` into `electron-builder.cjs` (and rewrite content from ES modules CommonJS modules). And it should work on node v20

**Comment by xuya227939** [comment]
Alright, thank you.
