### ISSUE TITLE
static assets

### ISSUE THREAD

**Issue by claudioluciano** [cawa-93/vite-electron-builder#112]
Hey i'm try to use a icon fot the system tray but the bundle is not copyng the asset, i already look on the vite config but none so far work.

Could you share some example of how use static assets for icons tray and window

**Comment by cawa-93** [comment]
This is because  assets inlined as base64 URLs

```js
import icon from './icon.png'
console.log(icon) // data:image/png;base64,...
```
To use the following image, instead of passing the path, you need to build it yourself: 
```js
import icon from './icon.png'
import {nativeImage, Tray} from 'electron'

new Tray(nativeImage.createFromDataURL(icon));
```

**Comment by davidwinter** [comment]
@cawa-93 if we need to set a static path to a file, like an icon for example, how could we achieve this?

https://www.electronjs.org/docs/latest/api/app#appsetaboutpaneloptionsoptions

To set the icon path in order to display the About dialog on Linux, you have to specify a path to the file, and a base64 URL won't work.
