### ISSUE TITLE
Use pnpm instead of npm

### ISSUE THREAD

**Issue by HermanLederer** [cawa-93/vite-electron-builder#557]
**Is your feature request related to a problem? Please describe.**
[pnpm](https://pnpm.io/) makes a better use of your drive, is faster than npm and results in more predictable behaviors (you cannot use packages not listed in the dependencies because they are not located in node_modules). I have seen a lot of people in the Vue ecosystem starting to use it and since this template is Vue by default I think it makes sense to switch as well.

**Describe the solution you'd like**
Remove npm lockfile, generate pnpm lockfile and replace all npm instructions with pnpm counterparts (cli is largely the same though)

**Additional context**
Comparison between npm and pnpm version if this template.

```bash
git clone https://github.com/cawa-93/vite-electron-builder.git npm
cd npm
npm install
```
results in a 580.8 MB directory

```bash
git clone https://github.com/cawa-93/vite-electron-builder.git pnpm
cd pnpm
rm package-lock.json
pnpm install
```

results in a 424.2 kB directory

I know that the space is still used somewhere else, but since those version of required packages can be reused for other node projects the space is utilized in a much better. If you have 2 electron apps based on this template you save 580.1 MB of space (size of node_modules with npm). If you have 3 of them you save 1160.2 MB and so on.

Will make a PR if the author approves.

**Comment by cawa-93** [comment]
Why pnpm? Why not yarn or something else? I understand that pnpm can have significant benefits for some people. But this template uses npm precisely because npm is a standard that comes with nodejs out of box. If you have a nodejs you have an npm. But there is no guarantee that a user or project has a pnpm or yarn or somyhing. In addition, migrate from npm to yarn is easier than from pnpm to yarn.

**Comment by HermanLederer** [comment]
That makes sense. I think it is safe to close the issue.

**Comment by seahindeniz** [comment]
@cawa-93 it is not just about migrating or looking for out of box support. Have you given any shot for PNPM's workspace feature before? 🤗 

Plus, installing pnpm is not a big issue, considering how powerful it is.
Your users (clever developers) just have to run `npm i -g pnpm` before running anything which should be even more easier to understand than getting familiar with the structure of this project.

**Comment by cawa-93** [comment]
@seahindeniz My opinion on this does not change: Everyone chooses the package manager he likes. As part of this template, I'm keeping neutral and using the built-in default.

**Comment by StarLederer** [comment]
Electron builder does not work with pnpm anyway ([electron-builder#6389](https://github.com/electron-userland/electron-builder/issues/6289#issuecomment-1042620422)) so it is probably not a good idea after all.

Besides it is probably too late now anyway because we are transitioning into the age of Rust and Deno so node package managers will not matter

**Comment by seahindeniz** [comment]
@StarLederer could you elaborate more for the second bit about the Rust age? Referring to Tauri or something else?

**Comment by seahindeniz** [comment]
If so, package managers still matters even for Tauri, IMO. To me, Deno isn't a good choice considering the dependency referencing issue. There's also Bun, will probably ship PNPM like package managing system, according to this [tweet](https://twitter.com/jarredsumner/status/1586667899959136256).
Moreover, I'm actually considering replacing Tauri with Electron because Tauri, still not mature enough and lacks some crucial features/plugins and there's also the learning curve for Rust for the backend part.
Cross-platform support is still hard for implementing solutions because there are bugs that prevent you implementing a solution that doesn't work on Linux but works on OSX
