### ISSUE TITLE
No Ukraine

### ISSUE THREAD

**Issue by nabychan** [cawa-93/vite-electron-builder#797]
**Describe the bug**
Ukraine is in the README.

**Expected behavior**
No Ukraine or anything else that has nothing to do with coding.

**Comment by cawa-93** [comment]
It would be easier for everyone to bury their heads in the sand and not think about complicated things

**Comment by nabychan** [comment]
You think you are the God?
You think this is the right place to make a sound?
What you do here is making thing complicated.
You can make your sound in twitter, youtube or other platforms, but you should not pollute github

**Comment by cawa-93** [comment]
@nabychan Politics is when you think about the reasons. I'm talking about facts. You can think of it this way:
I am the only one maintainer of the project. There is a war in my city. Every day houses explode. If I am killed tomorrow, this project will be left without support. 🤷‍♂️  Consider these risks before using this project

**Comment by nabychan** [comment]
So you know what is open source?

**Comment by aerotoad** [comment]
@cawa-93 Is the maintainer of this project and as such can show his support for whatever he considers right on the project's readme, because that's how freedom of speech works.
@nabychan You're free to complain as well, but it doesn't mean they have to listen.

As a maintainer of another project I have to say that if you don't like what you read, you can go somewhere else instead of reading it.
