### ISSUE TITLE
How to secure the source code

### ISSUE THREAD

**Issue by peter-rb2** [cawa-93/vite-electron-builder#846]
**Describe the bug**

Hi, I packaged the app with electron builder on windows, but inside the package folder i can see the souce code in the renderer folder were obfuscated but the codes inside the main and preload folder are not , so can you point out how can I secure the code in those two folders? thanks

**Comment by cawa-93** [comment]
No code is obfuscated or protected in any package. What you called obfucation is the usual minification (since the `renderer` is packaged as a web application vite tries to reduce the size of the output files for performance).

Any kind of source code protection is not the goal of this template. But it should be compatible with some general solutions for this case.
