### ISSUE TITLE
Bundle 3rd part modules in the preload script to allow use when sandboxing is enabled

### ISSUE THREAD

**Issue by glocore** [cawa-93/vite-electron-builder#880]
**Is your feature request related to a problem? Please describe.**
When sandboxing is enabled, we can't `require()` an external module in the preload script. The current config bundles up all local files so that we can split our preload source code into multiple files (nice 👍). But it would be awesome if we could also use 3rd party modules such as [`electron-better-ipc`](https://github.com/sindresorhus/electron-better-ipc) inside our preload script while in sandbox mode.

**Describe the solution you'd like**
Bundle 3rd party dependencies in the preload script output, similar to how we're bundling our local source code.

**Describe alternatives you've considered**
Disabling sandboxing is the only solution for now.

**Comment by cawa-93** [comment]
Previously it works exacly as you described. But this led to numerous problems (https://github.com/cawa-93/vite-electron-builder/issues/664, https://github.com/cawa-93/vite-electron-builder/issues/655, https://github.com/cawa-93/vite-electron-builder/issues/613), because there are a huge number of packages that he will not be able to fully bundle. Usually these are packages that depend on native APIs directly or transitively.

If it not problem for your case, You can set [`ssr.noExternal: true`](https://vitejs.dev/config/ssr-options.html#ssr-noexternal). It
- Treat all dependencies as noExternal
- Throw an error if any Node.js built-ins are imported

**Comment by glocore** [comment]
Makes sense, thanks for the explanation!
